//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class messageEntities : DbContext
    {
        public messageEntities()
            : base("name=messageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Guestbooks> Guestbooks { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<FileContent> FileContent { get; set; }
        public virtual DbSet<ForumAlbum> ForumAlbum { get; set; }
        public virtual DbSet<ForumArticle> ForumArticle { get; set; }
        public virtual DbSet<ForumMessage> ForumMessage { get; set; }
    }
}
